### ISSUE TITLE
关于传送门物理和渲染的小问题

### ISSUE THREAD

**Issue by Jack12xl** [cflw/taichi_raytracingportal#1]
Hi,
我是taichi助教，总得来说作业写得很好！

就是想问下，我注意到代码里渲染把门当作椭圆，但物理上算和其他球碰撞的时候没有严格把门当作一个椭圆来处理对嘛

**Comment by cflw** [comment]
是的。
代码本身就是模仿《传送门》写的，渲染时是个椭圆的洞，物理计算时是个矩形的洞。因为原作是个解谜游戏，允许适当穿模以提升解谜流畅性。所以游戏怎么实现的我就照着写。

**Comment by Jack12xl** [comment]
ok了解了
