### ISSUE TITLE
关于运行

### ISSUE THREAD

**Issue by Jack12xl** [cflw/taichi_raytracingportal#2]
注意到[这里](https://github.com/cflw/taichi_raytracingportal/blob/e697cde6a1d52939d97a45a557d65478cb531090/%E5%9C%BA%E6%99%AF0.py#L31)设置了输出路径, 建议把路径改成项目本地相对路径，不然用户没有该路径会报错😂

**Comment by cflw** [comment]
我写了2种输出方式，一个窗口输出，一个视频输出。
视频输出最后写完最后测试，测试完没有改回窗口输出，直接提交了。

**Comment by Jack12xl** [comment]
没事，问题不大
